runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /(|compile|fmt|share)
  script: _go_app
- url: /p/.+
  script: _go_app
