version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: go version
      - run: go mod download
      - run: go test -v
      
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud app deploy app.yaml

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
